documentation improvements
ecadlabs/signatory pull request #278
Opened 2023-01-23 05:32 UTC by stephengaudet

2023-01-23 18:04 UTC, AbineshECAD commented on docs/cli.md
> +Once the key is imported and made active, the value of the secret key in octez-client configuration is replaced with the key's URI in Signatory:
Please add the `octez-client import` command here.

2023-01-24 20:21 UTC, AbineshECAD requested changes
I will approve once the command is added 
https://github.com/ecadlabs/signatory/pull/278/files#r1084380508

2023-01-24 21:27 UTC, stephengaudet commented
> I will approve once the command is added https://github.com/ecadlabs/signatory/pull/278/files#r1084380508

I believe I have on line 119

2023-01-24 22:29 UTC, AbineshECAD approved these changes

2023-01-24 22:29 UTC, merged